name: "nexus"

packages:
  - packages/**

command:
  bootstrap:
    enforceLockfile: true

    environment:
      sdk: "^3.5.0"

    hooks:
      post: melos run gen-l10n && melos run gen

scripts:
  get:
    description: get dependencies (no lockfile update, linking)
    exec: dart pub get
  upgrade:
    description: upgrade dependencies
    exec: dart pub upgrade --major-versions
  clean:
    description: clean project
    exec: flutter clean
    packageFilters:
      flutter: true
  custom_lint:
    description: run custom lint
    exec: dart run custom_lint --fatal-infos
    packageFilters:
      dependsOn:
        - custom_lint # All packages _should_ depend on `custom_lint`, but they don't yet.
  gen-l10n:
    description: generate l10n files
    exec: flutter gen-l10n
    packageFilters:
      flutter: true
  gen:
    description: run build_runner
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn:
        - build_runner
  gen:watch:
    description: watch build_runner
    exec: dart run build_runner watch
    packageFilters:
      dependsOn:
        - build_runner
  test:
    description: run tests
    exec: dart run very_good_cli:very_good test --coverage --test-randomize-ordering-seed random
    packageFilters:
      dependsOn:
        - very_good_cli
