name: analysis_options
description: "Analyzer configuration for the Nexus team."
version: 0.0.1
homepage: https://PHS-TSA.github.io
documentation: https://github.com/PHS-TSA/nexus
issue_tracker: https://github.com/PHS-TSA/nexus/issues
repository: https://github.com/PHS-TSA/nexus.git

environment:
  sdk: ^3.5.0

dependencies:
  very_good_analysis: ^6.0.0

dev_dependencies:
  custom_lint: ^0.6.5
