name: legacy_checks
description: "Support legacy matchers in `package:checks` expectations."
version: 0.0.1
homepage: https://PHS-TSA.github.io
documentation: https://github.com/PHS-TSA/our_democracy
issue_tracker: https://github.com/PHS-TSA/our_democracy/issues
repository: https://github.com/PHS-TSA/our_democracy.git

environment:
  sdk: ^3.5.0

dependencies:
  checks: ^0.3.0
  matcher: ^0.12.16+1

dev_dependencies:
  very_good_analysis: ^6.0.0
  test: ^1.25.8
  very_good_cli: ^0.22.2
